# Generated by Django 6.0.2 on 2026-02-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_address_profile_business_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='contact_name',
            new_name='contact_first_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='contact_last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
