# Generated by Django 6.0.2 on 2026-02-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_contact_name_profile_contact_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='delivery_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='delivery_postcode',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
