# Generated by Django 6.0.2 on 2026-05-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_is_verified_profile_verification_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], default='APPROVED', max_length=20),
        ),
    ]
