# Generated by Django 6.0.2 on 2026-03-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='season',
            field=models.CharField(choices=[('SPRING', 'Spring'), ('SUMMER', 'Summer'), ('AUTUMN', 'Autumn'), ('WINTER', 'Winter'), ('ALL', 'All Season')], default='ALL', max_length=10),
        ),
    ]
