# Generated by Django 6.0.2 on 2026-03-13 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_product_allergen_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='allergen_info',
            new_name='other_allergen_info',
        ),
        migrations.AddField(
            model_name='product',
            name='allergens',
            field=models.ManyToManyField(blank=True, to='marketplace.allergen'),
        ),
    ]
