# Generated by Django 6.0.2 on 2026-03-17 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_product_season'),
        ('marketplace', '0004_allergen_and_more'),
    ]

    operations = [
    ]
