# Generated by Django 6.0.2 on 2026-03-18 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_initial_allergens'),
        ('marketplace', '0005_merge_0003_product_season_0004_allergen_and_more'),
    ]

    operations = [
    ]
