# Generated by Django 6.0.2 on 2026-03-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_rename_in_active_product_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_active',
            new_name='in_season',
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(max_length=200),
        ),
    ]
