# Generated by Django 6.0.2 on 2026-03-20 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_producerorderstatushistory'),
        ('marketplace', '0006_merge_20260318_1712'),
    ]

    operations = [
    ]
