# Generated by Django 6.0.2 on 2026-03-26 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_merge_20260320_1203'),
        ('marketplace', '0007_rename_is_active_product_in_season_and_more'),
    ]

    operations = [
    ]
