# Generated by Django 6.0.2 on 2026-04-12 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_merge_20260320_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_food',
            field=models.BooleanField(default=False),
        ),
    ]
