# Generated by Django 6.0.2 on 2026-03-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_merge_20260320_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_from_month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], help_text='Month when this product comes into season (leave blank for year-round).', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='available_to_month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], help_text='Last month this product is in season (leave blank for year-round).', null=True),
        ),
    ]
