# Generated by Django 6.0.2 on 2026-03-26 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_merge_20260326_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='in_season',
            new_name='is_active',
        ),
    ]
