# Generated by Django 6.0.2 on 2026-03-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_rename_in_season_product_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='harvest_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('each', 'Each'), ('kg', 'Kilogram'), ('g', 'Gram'), ('bunch', 'Bunch'), ('litre', 'Litre'), ('pack', 'Pack')], default='each', max_length=50),
        ),
    ]
