# Generated by Django 6.0.2 on 2026-03-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_normalize_harvest_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='harvest_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
