# Generated by Django 6.0.2 on 2026-03-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_merge_0008_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('each', 'Each'), ('kg', 'Kilogram'), ('g', 'Gram'), ('dozen', 'Dozen'), ('bunch', 'Bunch'), ('litre', 'Litre'), ('pack', 'Pack')], default='each', max_length=50),
        ),
    ]
