# Generated by Django 6.0.2 on 2026-04-17 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_category_is_food'),
        ('marketplace', '0015_alter_product_unit'),
    ]

    operations = [
    ]
