# Generated by Django 6.0.2 on 2026-04-21 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_merge_0008_category_is_food_0015_alter_product_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_food',
        ),
    ]
