# Generated by Django 6.0.2 on 2026-04-24 15:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_product_best_before_date_product_is_surplus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='surplus_discounted_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Automatically calculated discounted price.', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='surplus_stock_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Number of items available at discounted surplus price.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_from_month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], help_text='Month when this product comes into season.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_to_month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], help_text='Last month this product is in season.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='surplus_discount_percent',
            field=models.PositiveIntegerField(blank=True, help_text='Discount percentage for surplus deals. Must be between 10 and 50.', null=True),
        ),
    ]
