# Generated by Django 6.0.2 on 2026-04-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='verified_purchase',
            field=models.BooleanField(default=False),
        ),
    ]
