# Generated by Django 6.0.2 on 2026-04-22 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0017_remove_is_food_from_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_organic',
            field=models.BooleanField(default=False),
        ),
    ]
