# Generated by Django 6.0.2 on 2026-04-29 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_product_image'),
        ('marketplace', '0017_alter_producerorder_status'),
    ]

    operations = [
    ]
