# Generated by Django 6.0.2 on 2026-04-30

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0018_merge_20260429_1545"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="surplus_discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Amount reduced from the normal price. Stored as 0 when no deal is active.",
                max_digits=10,
            ),
        ),
    ]
