# Generated by Django 6.0.2 on 2026-04-30

from decimal import Decimal

from django.db import migrations


def backfill_surplus_discount_amount(apps, schema_editor):
    Product = apps.get_model("marketplace", "Product")

    for product in Product.objects.all():
        if product.is_surplus and product.surplus_discount_percent:
            discount_amount = (
                product.price * Decimal(product.surplus_discount_percent) / Decimal("100")
            ).quantize(Decimal("0.01"))
        else:
            discount_amount = Decimal("0.00")

        Product.objects.filter(pk=product.pk).update(
            surplus_discount_amount=discount_amount
        )


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0019_product_surplus_discount_amount"),
    ]

    operations = [
        migrations.RunPython(
            backfill_surplus_discount_amount,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
