# Generated by Django 6.0.2 on 2026-05-01 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0018_customerorderhistory'),
        ('marketplace', '0020_alter_order_status'),
    ]

    operations = [
    ]
