# Generated by Django 6.0.2 on 2026-05-01 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0018_customerorderhistory'),
        ('marketplace', '0020_alter_order_status'),
        ('marketplace', '0021_merge_20260430_2000'),
    ]

    operations = [
    ]
