# Generated by Django 6.0.2 on 2026-05-02 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0021_merge_20260501_1256'),
        ('marketplace', '0022_merge_20260501_1435'),
    ]

    operations = [
    ]
