# Generated by Django 6.0.2 on 2026-05-03 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0022_purchasereview'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchasereview',
            unique_together=set(),
        ),
    ]
