# Generated by Django 6.0.2 on 2026-05-03 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0019_product_low_stock_threshold_stocknotification'),
        ('marketplace', '0022_merge_20260501_1435'),
    ]

    operations = [
    ]
