# Generated by Django 6.0.2 on 2026-05-05 17:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0023_merge_20260502_1147'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='surplus_discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount reduced from the normal price.', max_digits=10),
        ),
        migrations.CreateModel(
            name='PurchaseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('delivery_rating', models.IntegerField()),
                ('packaging_rating', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecurringOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('WEEKLY', 'Every Week'), ('FORTNIGHTLY', 'Every Two Weeks')], default='WEEKLY', max_length=20)),
                ('order_day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of week order is generated (0=Monday)')),
                ('delivery_day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of week for delivery (0=Monday)')),
                ('delivery_address', models.CharField(max_length=255)),
                ('delivery_postcode', models.CharField(max_length=20)),
                ('payment_method', models.CharField(default='stripe', max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('next_order_date', models.DateField(blank=True, null=True)),
                ('last_generated', models.DateField(blank=True, null=True)),
                ('name', models.CharField(blank=True, help_text="Optional name e.g. 'Weekly veg box'", max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecurringOrderInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('MODIFIED', 'Modified'), ('PROCESSED', 'Processed'), ('SKIPPED', 'Skipped')], default='SCHEDULED', max_length=20)),
                ('order_number', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recurring_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='marketplace.recurringorder')),
            ],
            options={
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='RecurringOrderInstanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marketplace.recurringorderinstance')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.product')),
            ],
        ),
        migrations.CreateModel(
            name='RecurringOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.product')),
                ('recurring_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marketplace.recurringorder')),
            ],
        ),
    ]
