# Generated by Django 6.0.2 on 2026-05-03 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0023_alter_purchasereview_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
