# Generated by Django 6.0.2 on 2026-05-05 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0023_merge_20260502_1147'),
        ('marketplace', '0024_alter_review_options_alter_review_unique_together'),
    ]

    operations = [
    ]
