# Generated by Django 6.0.2 on 2026-05-06 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0024_alter_product_surplus_discount_amount_purchasereview_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringorder',
            name='card_expiry',
            field=models.CharField(blank=True, help_text='Card expiry MM/YY', max_length=5),
        ),
        migrations.AddField(
            model_name='recurringorder',
            name='card_last_four',
            field=models.CharField(blank=True, help_text='Last 4 digits of saved card', max_length=4),
        ),
        migrations.AddField(
            model_name='recurringorderinstance',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='recurringorderinstance',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recurringorderinstance',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='RecurringNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ORDER_SETUP', 'Recurring Order Set Up'), ('ORDER_UPCOMING', 'Order Processing Soon'), ('ORDER_PROCESSED', 'Order Processed'), ('PAYMENT_FAILED', 'Payment Failed'), ('PRODUCT_UNAVAILABLE', 'Product Unavailable'), ('PRODUCER_NOTICE', 'Producer Advance Notice')], max_length=30)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_notifications', to=settings.AUTH_USER_MODEL)),
                ('recurring_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='marketplace.recurringorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
