# Generated by Django 6.0.2 on 2026-05-05 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0023_merge_20260503_1440'),
        ('marketplace', '0025_merge_20260505_1325'),
    ]

    operations = [
    ]
