# Generated by Django 6.0.2 on 2026-05-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0025_recurringorder_card_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringorderitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
