# Generated by Django 6.0.2 on 2026-05-05 17:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0026_merge_20260505_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='surplus_discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount reduced from the normal price.', max_digits=10),
        ),
    ]
