# Generated by Django 6.0.2 on 2026-05-06 12:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0028_favouriteproducer_surplusdealnotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='estimated_unit_weight_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Estimated weight per unit in kg for surplus analytics.', max_digits=6),
        ),
        migrations.CreateModel(
            name='SurplusAnalyticsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('SAVED', 'Saved from waste'), ('UNSOLD', 'Unsold expired surplus')], max_length=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('estimated_weight_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('customer_saving', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surplus_analytics_records', to='marketplace.order')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surplus_analytics_records', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surplus_analytics_records', to='marketplace.product')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
