# Generated by Django 6.0.2 on 2026-05-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0028_refundrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='producerorder',
            name='order_type',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('BULK', 'Bulk'), ('RECURRING', 'Recurring')], default='NORMAL', max_length=20),
        ),
    ]
