# Generated by Django 6.0.2 on 2026-05-07 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0026_recurringorderitem_unit_price'),
        ('marketplace', '0028_refundrequest'),
    ]

    operations = [
    ]
