# Generated by Django 6.0.2 on 2026-05-07 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0029_merge_20260507_1002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refundrequest',
            options={},
        ),
    ]
