# Generated by Django 6.0.2 on 2026-05-07 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0029_add_producer_o'),
        ('marketplace', '0030_alter_refundrequest_options'),
    ]

    operations = [
    ]
