# Generated by Django 6.0.2 on 2026-05-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_add_images_and_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmstory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='community/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='community/'),
        ),
    ]
