"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-jvoi*b%e8-ymqey5fy63$kx1ikt0i9eyvdu$*2&+a*l#^i^5co"
)

DEBUG = os.getenv("DJANGO_DEBUG", "1") == "1"

ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'axes',

    'apps.accounts.apps.AccountsConfig',
    'apps.marketplace.apps.MarketplaceConfig',
    "apps.cart.apps.CartConfig",
    "apps.message.apps.MessageConfig",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/"templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.cart.context_processors.cart_item_count',
                'apps.marketplace.context_processors.active_surplus_deal_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import sys

if "test" in sys.argv:
    # Use fast in-memory SQLite for tests (no MySQL permissions needed)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": ":memory:",
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": os.getenv("DB_NAME", "brfn_db"),
            "USER": os.getenv("DB_USER", "brfn_user"),
            "PASSWORD": os.getenv("DB_PASSWORD", "123456789"),
            "HOST": os.getenv("DB_HOST", "127.0.0.1"),
            "PORT": os.getenv("DB_PORT", "3306"),
            "OPTIONS": {
                "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/London'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesBackend",
    "apps.accounts.backends.EmailBackend",
    "django.contrib.auth.backends.ModelBackend",
]


# ──────────────────────────────────────────────
# Session management
# ──────────────────────────────────────────────
SESSION_COOKIE_AGE = 1209600                # 2 weeks (when "remember me" is ticked)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True      # Default: expire on browser close
SESSION_COOKIE_HTTPONLY = True               # JS cannot read session cookie
SESSION_COOKIE_SAMESITE = "Lax"             # CSRF protection
SESSION_COOKIE_SECURE = not DEBUG           # HTTPS-only in production

LOGIN_URL = "accounts:login"


# ──────────────────────────────────────────────
# django-axes  – brute-force / rate-limiting
# ──────────────────────────────────────────────
AXES_FAILURE_LIMIT = 5                      # Lock after 5 bad attempts
AXES_COOLOFF_TIME = 1                       # 1-hour cooloff
AXES_LOCK_OUT_AT_FAILURE = True
AXES_RESET_ON_SUCCESS = True                # Reset counter after good login
AXES_LOCKOUT_PARAMETERS = ["username"]      # Lock per-account, not per-IP
AXES_USERNAME_FORM_FIELD = "username"       # Field name used in the login form
AXES_LOCKOUT_CALLABLE = "apps.accounts.views.axes_lockout_view"


# ──────────────────────────────────────────────
# Security logging
# ──────────────────────────────────────────────
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime} {levelname} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "security_file": {
            "class": "logging.FileHandler",
            "filename": BASE_DIR / "logs" / "security.log",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "security": {
            "handlers": ["console", "security_file"],
            "level": "INFO",
            "propagate": False,
        },
        "axes": {
            "handlers": ["console", "security_file"],
            "level": "INFO",
            "propagate": False,
        },
    },
}


# Media files (uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
